models/__init__.py
from peewee import SqliteDatabase
from .db import db
from .eventCalendar import EventCalendar
from .make import Make
from .achieve import Achieve

MODELS = [
    EventCalendar,
    Make,
    Achieve
]

# データベースの初期化関数
def initialize_database():
    db.connect()
    db.create_tables(MODELS, safe=True)
    db.create_tables([EventCalendar])
    db.close()

models/achieve.py
from peewee import Model, CharField,IntegerField, DateField
from .db import db

class Achieve(Model):
    year = IntegerField()
    month = IntegerField()
    day = IntegerField()
    title = CharField()
    todo = CharField()
    doneDay = CharField()

    class Meta:
        database = db

models/db.py
from peewee import SqliteDatabase

# データベース接続の定義
db = SqliteDatabase('my_database.db')

models/eventCalendar.py
from peewee import Model, CharField,IntegerField
from .db import db

class EventCalendar(Model):
    add_year = IntegerField()
    add_month = IntegerField()
    add_day = IntegerField()
    add_title = CharField()
    add_todo = CharField()

    class Meta:
        database = db
        

models/make.py
from .db import db
from peewee import Model, CharField

class Make(Model):
    title = CharField()

    class Meta:
        database = db

models/myCalendar.py
from peewee import Model, CharField, IntegerField
from .db import db

class MyCalendar(Model):
    name = CharField()
    date = IntegerField()

    class Meta:
        database = db

app.py
from flask import Flask, render_template
from routes import blueprints
from models import initialize_database

app = Flask(__name__)

initialize_database()

# 各Blueprintをアプリケーションに登録
for blueprint in blueprints:
    app.register_blueprint(blueprint)

# ホームページのルート
@app.route('/')
def calendar():
    
    return render_template('myCalendar')

if __name__ == '__main__':
    app.run(port=8081, debug=True)

routes/__init__.py
from .myCalendar import myCalendar_bp


# Blueprintをリストとしてまとめる
blueprints = [
  myCalendar_bp
]

routes/myCalendar.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for
import calendar
from datetime import datetime
from models.eventCalendar import EventCalendar
from models.make import Make
from models import Achieve


# Blueprintの作成
myCalendar_bp = Blueprint('myCalendar', __name__, url_prefix='')

@myCalendar_bp.route('/')
def list():
    #test出力
    print(f"今日の日付: {datetime.today().strftime('%Y-%m-%d')}")
    today = datetime.today()
    current_year = today.year
    current_month = today.month
    current_date = today.day

    # データベースから全てのタスクを取得
    tasks = EventCalendar.select()
    

    # 今日以降の期限のタスクをフィルタリングしたいけどできてない気がする
    upcoming_tasks = []
    for task in tasks:
        # 月と日から日付オブジェクトを作成
        task_date = datetime(current_year, task.add_month, task.add_day)
        today_date = datetime(current_year, current_month, current_date)
        
        # 過去の日付の場合は来年の日付として扱う
        if task_date < today_date:
            task_date = datetime(current_year + 1, task.add_month, task.add_day)
            
        # 更新された task_date を使って比較
        if task_date >= today_date:
            # タスクに並び替え用の日付情報を追加
            task.sort_date = task_date
            upcoming_tasks.append(task)
    
    # 日付でソート（更新された日付情報を使用）
    upcoming_tasks.sort(key=lambda x: x.sort_date)

    # 作成したカレンダーのタイトルを取得
    makes = Make.select()
    
    # 最初の3つのタスクのみを取得
    upcoming_tasks = upcoming_tasks[:3]
    


    return render_template('myCalendar.html', upcoming_tasks = upcoming_tasks, items=makes)

@myCalendar_bp.route("/create_calendar", methods=['GET'])
def createCalendar():
    # 現在の年月を取得
    # 日付のデータ取得
    month = int(request.args.get("month"))
    year = int(request.args.get("year"))
    move = int(request.args.get("move"))

    # 月の変更
    month += move

    # 年月の調整
    if month < 1:
        month = 12
        year -= 1
    elif month > 12:
        month = 1
        year += 1

    # カレンダー生成
    cal = calendar.Calendar()
    my_calendar = cal.monthdayscalendar(year, month)

    # データの取得

    events = EventCalendar.select().where(
            (EventCalendar.add_month == month) &
            (EventCalendar.add_year == year)
            ).order_by(EventCalendar.add_day.asc())

    
    # 結果を辞書に変換
    schedules = []
    for event in events:
        schedule = event.__data__  # モデルのインスタンスを辞書に変換
        schedules.append(schedule)

    # JSONでデータを返す
    return jsonify({"year": year, "month": month, "calendar": my_calendar, "schedules": schedules})


@myCalendar_bp.route('/add/<int:ymd>', methods=['GET', 'POST'])
def add(ymd):
    # 作成したカレンダーのタイトルを取得
    makes = Make.select()
    
    if request.method == 'POST':

        year = int(ymd / 10000)
        month = int((ymd - year * 10000) / 100)
        day = ymd - (year * 10000) - (month * 100)
        title = request.form['add_title']
        todo = request.form['add_todo']
        
        # 予定を保存
        event = EventCalendar(
            add_year=year,
            add_month=month,
            add_day=day,
            add_title=title,
            add_todo=todo
        )
        event.save()

        return redirect(url_for('myCalendar.list'))
    
    return render_template('myCalendar_add.html', ymd = ymd, makes=makes)

@myCalendar_bp.route('/edit/<string:eventCalendar_id>',methods=['GET','POST'])
def edit(eventCalendar_id):
    calendar=EventCalendar.get_or_none(EventCalendar.add_title==eventCalendar_id)
    if request.method=='POST':
        if not calendar:
            return redirect(url_for('myCalendar.list'))
        
        if request.form['completed'] == 'true':
            y = request.form['year']
            m = request.form['month']
            d = request.form['day']
            title = request.form['title']
            todo = request.form['todo']

            print('comp!!')

            dt = datetime.today()
            date = str(dt.year) + '/' + str(dt.month) + '/' + str(dt.day)

            Achieve.create(year=y, month=m, day=d, title=title, todo=todo, doneDay=date)


        calendar.add_year=request.form['year']
        calendar.add_month=request.form['month']
        calendar.add_day=request.form['day']
        calendar.add_title=request.form['title']
        calendar.add_todo=request.form['todo']
        calendar.save()
        return redirect(url_for('myCalendar.list'))
    return render_template('myCalendar_edit.html',eventCalendar_id=eventCalendar_id,calendar=calendar)

@myCalendar_bp.route('/achieve_list')
def achieve_list():
    achs = Achieve.select()

    return render_template('achieve_list.html', items=achs)

templates/achieve_list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>達成済みリスト</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='base-style.css') }}">
        <script type="text/javascript" src="../static/main.js"></script>
    </head>
    <body>
        <h1>達成済み</h1>
        <table>
            <thead>
                <tr>
                    <th>年</th>
                    <th>月</th>
                    <th>日</th>
                    <th>タイトル</th>
                    <th>内容</th> 
                    <th>達成日</th>           
                </tr>
            </thead>
            <tbody>
                {% for ach in items %}
                <tr>
                    <td>{{ ach.year }}</td>
                    <td>{{ ach.month }}</td>
                    <td>{{ ach.day }}</td>
                    <td>{{ ach.title }}</td>
                    <td>{{ ach.todo }}</td>
                    <td>{{ ach.doneDay }}</td>
                </tr>
                {% endfor %}
                <a href="/">トップページに戻る</a>
            </tbody>
        </table>
    </body>
</html>

templates/calendar_add.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>予定追加</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='base-style.css') }}">
</head>
<body>
    <h1>新しい予定を追加</h1>
    <ul class="breadcrumb">
        <li><a href="{{ url_for('index') }}">HOME</a></li>
        <li><a href="{{ url_for('myCalendar') }}">予定一覧</a></li>
        <li>予定登録</li>
    </ul>
    <form action="{{ url_for('calendar.add') }}" method="post">
        <label>名前: <input type="text" name="name" required></label><br>
        <label>日付: <input type="date" name="date" value="2025-01-01" min="2025-01-01" max="2025-01-31" required></label><br>
        <textarea id="business" name="plan" cols="200" row="5"></textarea>
        <button type="submit">追加</button>
    </form>
</body>
</html>

templates/calendar_edit.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>予定編集</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='base-style.css') }}">
</head>
<body>
    <h1>予定を編集</h1>
    <ul class="breadcrumb">
        <li><a href="{{ url_for('myCalendar') }}">HOME</a></li>
        <li><a href="{{ url_for('calendar.list') }}">予定一覧</a></li>
        <li>予定の編集</li>
    </ul>

    <form action="{{ url_for('calendar.edit',originalName=originalName,name=name,date=date,plan=plan) }}" method="post">
        <label>予定名: 
            <select name="calendar_id" required>
                {% for user in users %}
                    <option value="{{ calendar.id }}" {% if calendar.id == calendar.id %}selected{% endif %}>{{ calendar.name }}</option>
                {% endfor %}
            </select>
        </label><br>
        <label>予定: 
            <select name="calendar_id" required>
                {% for product in products %}
                    <option value="{{ calendar.id }}" {% if order.product.id == calendar.id %}selected{% endif %}>{{ product.name }}</option>
                {% endfor %}
            </select>
        </label><br>
        <button type="submit">保存</button>
    </form>
</body>
</html>

templates/calendar_list.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>予定一覧</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='base-style.css') }}">
</head>
<body>
    <h1>{{ originalName }}</h1>
    <ul class="breadcrumb">
        <li><a href="{{ url_for('myCalendar') }}">HOME</a></li>
        <li><a href="{{ url_for('calendar.list') }}">予定一覧</a></li>
    </ul>

    <a href="{{ url_for('calendar.add') }}">新規予定追加</a>
    <table>
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th>予定名</th>
                <th>日付</th>
                <th>予定内容</th>
            </tr>
        </thead>
        <tbody>
            {% for calendar in calendars %}
            <tr>
                <td><a href="{{ url_for('calendar.edit', originalName=originalName,name=name,date=date,plan=plan) }}">編集</a></td>
                <td>{{ calendar.name }}</td>
                <td>{{ calendar.date }}</td>
                <td>{{ calendar.plan }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

templates/calender_make.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>新規作成</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='base-style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='calender-form.css') }}">
</head>
<body>
    <h1>新規カレンダー作成</h1>
    <form action="{{ url_for('myCalendar.make') }}" method="post">
        <div class="form-group category">
        <label>カテゴリ: <input type="text" name="category" required></label><br>
        </div>
        <button type="submit">追加</button>
    </form>
</body>
</html>

templates/countdown.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>カウントダウン</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='base-style.css') }}">
</head>
<body>
    <h1>期限の近いタスク</h1>
    <div class="task-list">
        {% for task in tasks %}
        <li>
        <!-- 受け取った予定を全て表示 -->
            <div class="task-item">
                <div class="task-title">{{task.title}}</div>
                <div class="task-deadline">期限：{{task.month}}月{{task.day}}日</div>
            </div>
        </li>
        {% endfor %}
    </div>
</body>
</html>

<!-- こんな感じでpythonから受け渡すつもりです
@app.route('/countdown')
def countdown():
    tasks = [
        {'title': 'タスク1', 'month': 3, 'day': 20},
        {'title': 'タスク2', 'month': 3, 'day': 21},
        {'title': 'タスク3', 'month': 3, 'day': 22}
    ]
    return render_template('countdown.html', tasks=tasks)
-->

templates/myCalendar.html
<!DOCTYPE html>
<html lang="ja">
  <head>
      <meta charset="UTF-8">
      <title>カレンダー</title>
      <link rel="stylesheet" href="{{ url_for('static', filename='base-style.css') }}">
      <script type="text/javascript" src="/static/main.js"></script>
  </head>
  <body>
    <div class="calendar">
      <h1>Originalカレンダー</h1>
      <div class="select">
        <button id="last_month" class="move" onclick="changeMonth(-1)"></button>
        <div>
          <div id="title_month">current_month</div>
          <div id="title_year">current_year</div>
        </div>
        <button id="next_month" class="move" onclick="changeMonth(1)"></button>
      </div>
        <table class="calendar">
          <thead></thead>
          <tbody></tbody>
        </table>
    </div>
    <div>
      <div class="upcoming-tasks">
        <h2>期限の近いタスク</h2>
        {% if upcoming_tasks %}
          <ul class="task-list">
            {% for task in upcoming_tasks %}
              <li class="task-item">
              <div class="task-deadline">期限：{{ task.add_month }}月{{ task.add_day }}日</div>
              <div class="task-title">タイトル:{{ task.add_title }}</div>  
              <div class="task-content">内容:{{ task.add_todo }}</div>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <p>予定を追加してください</p>
        {% endif %}
      </div>
    </div>
  <div>
  <div class="complete_task">
    <a href="/achieve_list">達成済みリスト</a>
  </div>
    </body>
</html>

templates/myCalendar_add.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>ToDo追加</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='base-style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='todo-form.css') }}">
</head>
<body>
    <h1>新しいスケジュールを追加</h1>

     <form action="{{ url_for('myCalendar.add', ymd = ymd) }}" method="post">
        <div class="form-group title">
        <label>タイトル: <input type="text" name="add_title" required></label><br>
        </div>
        <div class="form-group detail">
        <label>詳細: <input type="text" name="add_todo" required></label><br>
        </div>
        <button type="submit">追加</button>
    </form>
</body>
</html>

templates/myCalendar_edit.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>予定編集</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='base-style.css') }}">
    <script type="text/javascript" src="../static/main.js"></script>
</head>
<body>
    <h1>予定を編集</h1>
        <li><a href="{{ url_for('myCalendar.list') }}">予定一覧</a></li>
        <li>編集</li>
    </ul>

    <form action="{{ url_for('myCalendar.edit', eventCalendar_id=eventCalendar_id) }}" method="post">
        <label>年: <input id="year" type="number" name="year" value="{{ calendar.add_year }}" required></label><br>
        <label>月: <input id="month" type="number" name="month" value="{{ calendar.add_month }}" required></label><br>
        <label>日: <input id="day" type="number" name="day" value="{{ calendar.add_day }}" required></label><br>
        <label>タイトル: <input id="title" type="text" name="title" value="{{ calendar.add_title }}" required></label><br>
        <label>内容: <input id="todo" type="text" name="todo" value="{{ calendar.add_todo }}" required></label><br>
        <label style="display: none;">完了: <input type="text" name="completed" id="complete"></label>
        <input type="checkbox" onclick="completedEvent()" id="cb">完了<br>
        <button type="submit" name="status" value="pending">保存</button>
        <!-- <button type="submit" name="status" value="completed" onclick="completedEvent()">完了</button> -->
    </form>
    <script>
        function completedEvent() {
            var cb = document.getElementById('cb')
            var comp = document.getElementById('complete');
            if (cb.checked) {
                comp.value = 'true';
            } else {
                comp.value = '';
            }
        }


        document.getElementsByName('status').addEventListener("click", function () {
        // 入力データの取得
        const month = document.getElementById('month').value;
        const day = document.getElementById('day').value;
        const title = document.getElementById('title').value;
        const todo = document.getElementById('todo').value;

        // クエリパラメータを生成
        const queryParams = new URLSearchParams({
            month: month,
            day: day,
            title: title,
            todo: todo
        }).toString();

        // 現在の日付を取得して隠し入力フィールドとしてフォームに追加
        const now = new Date();
        const completedDate = now.toISOString().split("T")[0]; // 現在の日付 (YYYY-MM-DD)
        
        const form = document.querySelector("form");
        const input = document.createElement("input");
        input.type = "hidden";
        input.name = "completed_date";
        input.value = completedDate;
        form.appendChild(input);

        // 遷移先URLの生成
        window.location.href = "{{ url_for('myCalendar.edit', eventCalendar_id=calendar) }}?" + queryParams;
    });
    </script>
</body>
</html>

templates/myCalendar_list.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>予定一覧</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='base-style.css') }}">
</head>
<body>
    <h1>{{ add_title }}</h1>
    <ul class="breadcrumb">
        <li><a href="{{ url_for('myCalendar') }}">HOME</a></li>
        <li><a href="{{ url_for('myCalendar.list') }}">予定一覧</a></li>
    </ul>

    <a href="{{ url_for('myCalendar.add') }}">新規予定追加</a>
    <table>
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th>月</th>
                <th>日</th>
                <th>タイトル</th>
                <th>内容</th>            
            </tr>
        </thead>
        <tbody>
            {% for cal in cal %}
            <tr>
                <td><a href="{{ url_for('myCalendar.edit',EventCalendar.id=calendar_id) }}">編集</a></td>
                <td>{{ cal.month }}</td>
                <td>{{ cal.day }}</td>
                <td>{{ cal.title }}</td>
                <td>{{ cal.todo }}</td>
            </tr>
            {% endfor %}
            <button onclick="javascript:window.history.back(-1);return false;">戻る</button>
        </tbody>
    </table>
</body>
</html>

templates/register.html
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>登録！</title>
  </head>
  <body>
    <img src="images/firefox-icon.png" alt="テスト画像" />
  </body>
</html>

templates/touroku.html
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>登録</title>
  </head>
  <body>
    <img src="images/firefox-icon.png" alt="テスト画像" />
  </body>
</html>